"""Build the browser-ready localized architecture project dataset.

The per-project ``context.csv`` files contain Chinese source content and
``assets/arch/translations.en.json`` contains the English localization.
``assets/arch/projectsData.js`` is a generated artifact kept as a classic script
so the static site also works when opened directly from the filesystem.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
import sys
from pathlib import Path
from typing import Iterable


PI = 3.1415926535897932384626
EE = 0.00669342162296594323
EARTH_RADIUS = 6378245.0
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".avif"}
GENERATED_HEADER = "// Generated by scripts/build_arch_data.py. Do not edit directly.\n"
LOCALIZED_FIELDS = (
    "title",
    "subtitle",
    "time",
    "location",
    "type",
    "area",
    "far",
    "greening",
    "designer",
    "description",
)
ENGLISH_TRANSLATION_FIELDS = {
    "title",
    "subtitle",
    "location",
    "type",
    "designer",
    "description",
}


def _transform_lat(x: float, y: float) -> float:
    result = -100.0 + 2.0 * x + 3.0 * y + 0.2 * y * y + 0.1 * x * y
    result += 0.2 * math.sqrt(abs(x))
    result += (20.0 * math.sin(6.0 * x * PI) + 20.0 * math.sin(2.0 * x * PI)) * 2.0 / 3.0
    result += (20.0 * math.sin(y * PI) + 40.0 * math.sin(y / 3.0 * PI)) * 2.0 / 3.0
    result += (160.0 * math.sin(y / 12.0 * PI) + 320 * math.sin(y * PI / 30.0)) * 2.0 / 3.0
    return result


def _transform_lon(x: float, y: float) -> float:
    result = 300.0 + x + 2.0 * y + 0.1 * x * x + 0.1 * x * y
    result += 0.1 * math.sqrt(abs(x))
    result += (20.0 * math.sin(6.0 * x * PI) + 20.0 * math.sin(2.0 * x * PI)) * 2.0 / 3.0
    result += (20.0 * math.sin(x * PI) + 40.0 * math.sin(x / 3.0 * PI)) * 2.0 / 3.0
    result += (150.0 * math.sin(x / 12.0 * PI) + 300.0 * math.sin(x / 30.0 * PI)) * 2.0 / 3.0
    return result


def _outside_china(longitude: float, latitude: float) -> bool:
    return not (73.66 < longitude < 135.05 and 3.86 < latitude < 53.55)


def gcj02_to_wgs84(longitude: float, latitude: float) -> tuple[float, float]:
    """Convert GCJ-02 coordinates to WGS-84 for the Leaflet base map."""
    if _outside_china(longitude, latitude):
        return longitude, latitude

    delta_latitude = _transform_lat(longitude - 105.0, latitude - 35.0)
    delta_longitude = _transform_lon(longitude - 105.0, latitude - 35.0)
    latitude_radians = latitude / 180.0 * PI
    magic = math.sin(latitude_radians)
    magic = 1 - EE * magic * magic
    square_root_magic = math.sqrt(magic)
    delta_latitude = (
        delta_latitude * 180.0
        / ((EARTH_RADIUS * (1 - EE)) / (magic * square_root_magic) * PI)
    )
    delta_longitude = (
        delta_longitude * 180.0
        / (EARTH_RADIUS / square_root_magic * math.cos(latitude_radians) * PI)
    )
    converted_latitude = latitude + delta_latitude
    converted_longitude = longitude + delta_longitude
    return longitude * 2 - converted_longitude, latitude * 2 - converted_latitude


def read_csv(path: Path) -> list[list[str]]:
    """Read legacy CSV files while preserving their original Chinese encoding."""
    for encoding in ("utf-8-sig", "utf-8", "gb18030"):
        try:
            with path.open("r", encoding=encoding, newline="") as file:
                return list(csv.reader(file))
        except UnicodeDecodeError:
            continue
    raise ValueError(f"Unsupported text encoding: {path}")


def list_project_images(directory: Path) -> list[Path]:
    if not directory.is_dir():
        return []
    return sorted(
        path for path in directory.iterdir()
        if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS
    )


def _parse_coordinates(values: Iterable[str]) -> list[float]:
    parts = [part.strip() for part in values if part.strip()]
    if len(parts) == 1:
        parts = [part.strip() for part in parts[0].split(",")]
    if len(parts) < 2:
        return [0, 0]

    try:
        longitude, latitude = float(parts[0]), float(parts[1])
    except ValueError:
        return [0, 0]

    converted_longitude, converted_latitude = gcj02_to_wgs84(longitude, latitude)
    return [converted_latitude, converted_longitude]


def normalize_area(value: str) -> str:
    match = re.fullmatch(r"\s*([\d,]+(?:\.\d+)?)\s*(?:m2|m²|㎡)?\s*", value, re.IGNORECASE)
    if not match:
        return value

    number = match.group(1).replace(",", "")
    integer, separator, decimal = number.partition(".")
    formatted_number = f"{int(integer):,}"
    if separator and decimal:
        formatted_number = f"{formatted_number}.{decimal}"
    return f"{formatted_number} m²"


def chinese_text(value: str) -> str:
    """Remove a legacy inline English translation from a Chinese source field."""
    return re.split(r"\s+/\s+", value, maxsplit=1)[0].strip()


def parse_project(project_directory: Path, assets_directory: Path) -> dict[str, object]:
    rows = read_csv(project_directory / "context.csv")
    project: dict[str, object] = {
        "id": project_directory.name,
        "title": "",
        "subtitle": "",
        "time": "",
        "location": "",
        "coords": [0, 0],
        "type": "",
        "area": "",
        "far": "",
        "greening": "",
        "designer": "",
        "description": "",
        "images": [],
    }
    description_lines: list[str] = []
    description_started = False

    for row in rows:
        if not row or not any(cell.strip() for cell in row):
            continue

        key = row[0].strip()
        values = [cell.strip() for cell in row[1:]]
        value = values[0] if values else ""

        if description_started:
            description_lines.append(",".join(cell.strip() for cell in row).strip())
        elif "文本" in key or "描述" in key:
            description_started = True
            description_lines.append(",".join(values).strip())
        elif "名称" in key or key == "项目":
            project["title"] = value
        elif "副标题" in key:
            project["subtitle"] = value
        elif "时间" in key:
            project["time"] = value.replace("-", "–")
        elif "位置" in key or "地点" in key:
            project["location"] = re.sub(r"\s*·\s*", "·", value)
        elif "坐标" in key:
            project["coords"] = _parse_coordinates(values)
        elif "功能" in key or "类型" in key:
            project["type"] = re.sub(r"\s*\|\s*", " / ", value)
        elif "面积" in key:
            project["area"] = normalize_area(value)
        elif "容积率" in key:
            project["far"] = value
        elif "绿地" in key or "绿化" in key:
            project["greening"] = value
        elif "设计" in key or "人员" in key:
            project["designer"] = value

    if not project["title"] and rows and len(rows[0]) > 1:
        project["title"] = rows[0][1].strip()
    if not project["subtitle"] and len(rows) > 1 and len(rows[1]) > 1:
        project["subtitle"] = rows[1][1].strip()

    normalized_description_lines = [
        line.replace("\r\n", "\n").replace("\r", "\n")
        for line in description_lines
        if line
    ]
    project["description"] = "\n\n".join(normalized_description_lines)
    project["images"] = [
        path.relative_to(assets_directory.parents[1]).as_posix()
        for path in list_project_images(project_directory / "pic")
    ]
    validate_project(project, project_directory)
    return project


def validate_project(project: dict[str, object], directory: Path) -> None:
    if not project["title"]:
        raise ValueError(f"Missing project title: {directory}")
    if not project["images"]:
        raise ValueError(f"Project has no supported images: {directory}")

    coordinates = project["coords"]
    if coordinates != [0, 0]:
        latitude, longitude = coordinates
        if not (-90 <= latitude <= 90 and -180 <= longitude <= 180):
            raise ValueError(f"Invalid coordinates in {directory}: {coordinates}")


def load_english_translations(assets_directory: Path) -> dict[str, dict[str, str]]:
    translation_path = assets_directory / "translations.en.json"
    translations = json.loads(translation_path.read_text(encoding="utf-8"))
    if not isinstance(translations, dict):
        raise ValueError(f"English translations must be an object: {translation_path}")
    return translations


def localize_project(
    project: dict[str, object],
    english_translation: dict[str, str],
) -> dict[str, object]:
    missing_fields = ENGLISH_TRANSLATION_FIELDS - set(english_translation)
    if missing_fields:
        raise ValueError(
            f"Project {project['id']} is missing English fields: {sorted(missing_fields)}"
        )

    chinese_locale = {field: project[field] for field in LOCALIZED_FIELDS}
    chinese_locale["title"] = chinese_text(str(chinese_locale["title"]))
    chinese_locale["subtitle"] = chinese_text(str(chinese_locale["subtitle"]))

    english_locale = {
        field: project[field]
        for field in ("time", "area", "far", "greening")
    }
    english_locale.update({
        field: str(english_translation[field]).strip()
        for field in ENGLISH_TRANSLATION_FIELDS
    })
    english_locale = {
        field: english_locale.get(field, "")
        for field in LOCALIZED_FIELDS
    }

    return {
        "id": project["id"],
        "coords": project["coords"],
        "images": project["images"],
        "locales": {
            "zh": chinese_locale,
            "en": english_locale,
        },
    }


def build_projects(assets_directory: Path) -> list[dict[str, object]]:
    project_directories = sorted(
        path for path in assets_directory.iterdir()
        if path.is_dir() and (path / "context.csv").is_file()
    )
    translations = load_english_translations(assets_directory)
    source_projects = [parse_project(path, assets_directory) for path in project_directories]
    source_ids = {str(project["id"]) for project in source_projects}
    translation_ids = set(translations)
    if source_ids != translation_ids:
        raise ValueError(
            "English translation ids do not match project sources: "
            f"source={sorted(source_ids)}, translations={sorted(translation_ids)}"
        )
    return [
        localize_project(project, translations[str(project["id"])])
        for project in source_projects
    ]


def serialize_projects(projects: list[dict[str, object]]) -> str:
    payload = json.dumps(projects, ensure_ascii=False, indent=2)
    return f"{GENERATED_HEADER}window.ARCH_PROJECTS = {payload};\n"


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when projectsData.js is not synchronized with the CSV sources.",
    )
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    repository_root = Path(__file__).resolve().parents[1]
    assets_directory = repository_root / "assets" / "arch"
    output_path = assets_directory / "projectsData.js"

    projects = build_projects(assets_directory)
    generated_content = serialize_projects(projects)

    if arguments.check:
        current_content = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        if current_content != generated_content:
            print("projectsData.js is out of date. Run scripts/build_arch_data.py.", file=sys.stderr)
            return 1
        print(f"Validated {len(projects)} architecture projects.")
        return 0

    output_path.write_text(generated_content, encoding="utf-8", newline="\n")
    print(f"Generated {output_path} with {len(projects)} projects.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
