"""Build the English architecture dataset from each project's context.csv.

The generated classic script works on GitHub Pages and from a local static server.
Run with --check to verify that the committed output matches its CSV sources.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.webp', '.avif'}
GENERATED_HEADER = '// Generated by scripts/build_arch_data.py. Do not edit directly.\n'
FIELDS = {
    'Project': 'title',
    'Subtitle': 'subtitle',
    'Period': 'time',
    'Location': 'location',
    'Type': 'type',
    'Area': 'area',
    'FAR': 'far',
    'Green Cover': 'greening',
    'Designer': 'designer',
    'Description': 'description',
}


def build_project(directory: Path, repository_root: Path) -> dict[str, object]:
    source = directory / 'context.csv'
    with source.open(encoding='utf-8-sig', newline='') as file:
        rows = [row for row in csv.reader(file) if row and any(cell.strip() for cell in row)]
    entries = {row[0].strip(): row[1:] for row in rows}
    missing = sorted(set(FIELDS) - entries.keys())
    if missing:
        raise ValueError(f'{source}: missing fields {missing}')

    project: dict[str, object] = {'id': directory.name}
    for label, field in FIELDS.items():
        project[field] = entries[label][0].strip() if entries[label] else ''
    if not project['title'] or not project['description']:
        raise ValueError(f'{source}: title and description are required')

    coordinates = entries.get('Coordinates', [])
    if len(coordinates) >= 2:
        longitude, latitude = (float(value) for value in coordinates[:2])
        if not (-180 <= longitude <= 180 and -90 <= latitude <= 90):
            raise ValueError(f'{source}: invalid coordinates')
        project['coords'] = [latitude, longitude]

    image_directory = directory / 'pic'
    images = sorted(
        path for path in image_directory.iterdir()
        if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS
    ) if image_directory.is_dir() else []
    if not images:
        raise ValueError(f'{source}: no project images')
    project['images'] = [path.relative_to(repository_root).as_posix() for path in images]
    return project


def build_projects(repository_root: Path) -> list[dict[str, object]]:
    assets = repository_root / 'assets' / 'arch'
    directories = sorted(path for path in assets.iterdir() if (path / 'context.csv').is_file())
    if not directories:
        raise ValueError('No architecture project sources found')
    return [build_project(path, repository_root) for path in directories]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check generated data without writing it')
    arguments = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    output = root / 'assets' / 'arch' / 'projectsData.js'
    projects = build_projects(root)
    generated = GENERATED_HEADER + 'window.ARCH_PROJECTS = ' + json.dumps(projects, ensure_ascii=False, indent=2) + ';\n'
    if arguments.check:
        if not output.exists() or output.read_text(encoding='utf-8') != generated:
            print('projectsData.js is out of date. Run scripts/build_arch_data.py.', file=sys.stderr)
            return 1
        print(f'Validated {len(projects)} architecture projects.')
        return 0
    output.write_text(generated, encoding='utf-8')
    print(f'Generated {len(projects)} architecture projects.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
